### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onMessage' of undefined

### ISSUE THREAD

**Issue by quiescentsam** [iamkaiff/Cookie-Deletion-with-Script#1]
![image](https://user-images.githubusercontent.com/15881160/79705666-79dc5c00-8284-11ea-8119-92224a9113b6.png)

**Comment by iamkaiff** [comment]
Check your chrome version and give the domain name clearly

**Comment by quiescentsam** [comment]
1. Reopen the issue 
2. show an example of usage in README.md
